version: '1.0'

steps:
  HelmLint:
    title: Helm Lint all values yaml file under chart-values/
    image: 'codefresh/cfstep-helm'
    commands:
      - cd event-driven/chart-values/
      - helm lint -f confluent-chart-values.yaml
      - helm lint -f minio-chart-values.yaml