apiVersion: v1
kind: Pod
metadata:
  name: datalab
  labels:
    app: datalab
spec:
  containers:
  - name: datalab
    image: gcr.io/cloud-datalab/datalab:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      name: notebook-port
      protocol: TCP
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
---
kind: Service
apiVersion: v1
metadata:
  name: datalab
spec:
  type: LoadBalancer
  selector:
    app: datalab
  ports:
  - name: datalab-port
    protocol: TCP
    port: 8080
    targetPort: 8080