apiVersion: v1
kind: Service
metadata:
  name: data-warehousing-zeppelin
  labels:
    app: zeppelin
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: web
  selector:
    app: zeppelin
    release: data-warehousing
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-warehousing-zeppelin
  labels:
    app: zeppelin
    release: data-warehousing
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
        release: data-warehousing
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: zeppelin
          image: dylanmei/zeppelin:0.7.2
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1