apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnailer
  labels:
    app: thumbnailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnailer
  template:
    metadata:
      labels:
        app: thumbnailer
    spec:
      containers:
      - name: thumbnailer
        image: azureq/thumbnailer:1.0
        imagePullPolicy: Always
        env:
        - name: MINIO_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: blobstore-index-minio
              key: accesskey
        - name: MINIO_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: blobstore-index-minio
              key: secretkey
        - name: MINIO_ENDPOINT
          value: blobstore-index-minio:9000
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: blobstore-index-confluent-cp-kafka:9092
        - name: IMAGES_BUCKET_EVENT_TOPIC
          value: images-bucket-event
        - name: THUMBNAILS_EVENT_TOPIC
          value: thumbnails-event
        - name: MONGODB_ROOT_USER
          value: root
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blobstore-index-mongodb
              key: mongodb-root-password
        - name: MONGODB_SERVER
          value: blobstore-index-mongodb:27017
        - name: MONGODB_DATABASE
          value: mydb
        - name: MONGODB_METADATA_TABLE
          value: metadata